"""add_delivery_method_to_order

Revision ID: bc818893059c
Revises: 28efae713454
Create Date: 2026-02-06 16:28:17.536961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc818893059c'
down_revision: Union[str, Sequence[str], None] = '28efae713454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Cria o tipo ENUM no Postgres primeiro
    delivery_method_enum = sa.Enum('DELIVERY', 'PICKUP', name='deliverymethod')
    delivery_method_enum.create(op.get_bind(), checkfirst=True)

    # 2. Adiciona a coluna permitindo NULL temporariamente para não travar nos dados antigos
    op.add_column('order', sa.Column('delivery_method', delivery_method_enum, nullable=True))

    # 3. Preenche todos os pedidos antigos com 'PICKUP' (ou o padrão que desejar)
    op.execute("UPDATE \"order\" SET delivery_method = 'PICKUP' WHERE delivery_method IS NULL")

    # 4. Agora que não há mais nulos, define a coluna como NOT NULL
    op.alter_column('order', 'delivery_method', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivery_method')
    # ### end Alembic commands ###
