"""Add delivery radius and geo fields

Revision ID: d6e6f2a061b5
Revises: 5855682b09a5
Create Date: 2026-02-03 14:15:39.776604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6e6f2a061b5'
down_revision: Union[str, Sequence[str], None] = '5855682b09a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('max_delivery_radius', sa.Float(), nullable=False, server_default="10.0"))
    op.add_column('bot', sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bot', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bot', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('bot', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'longitude')
    op.drop_column('bot', 'latitude')
    op.drop_column('bot', 'address')
    op.drop_column('bot', 'cep')
    op.drop_column('bot', 'max_delivery_radius')
    # ### end Alembic commands ###
